services:
  app:
    container_name: image-to-get-location-llm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8089:8080
    env_file:
      - .env
    networks:
      - image-to-get-location-llm

networks:
  image-to-get-location-llm:
